# inspired from https://github.com/vegasbrianc/prometheus/blob/master/docker-compose.yml
version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  dimres:
    build: .
    # ports:
    #   - "9901:9901"
    volumes:
      - ./compose/resource_model_exporter/:/resources/
    environment:
      - PROM_ENDPOINT=localhost:9090
      - REGRESSION_MIN_ROI=5m
      - REGRESSION_MAX_ROI=5m
      - SAMPLING_INTERVAL=15s
    depends_on:
      - prometheus
    restart: always
    network_mode: "host"

  prometheus:
    image: prom/prometheus:v2.27.1
    volumes:
      - ./compose/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    # ports:
    #   - 9090:9090
    # links:
    #   - cadvisor:cadvisor
    depends_on:
      - cadvisor
    restart: always
    network_mode: "host"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    # ports:
    #   - 9100:9100
    restart: always
    network_mode: "host"
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    # ports:
    #   - 8080:8080
    restart: always
    network_mode: "host"
    deploy:
      mode: global

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    # ports:
    #   - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./compose/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./compose/grafana/config.monitoring
    restart: always
    network_mode: "host"
