global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    metric_relabel_configs:
    - source_labels: [container_label_com_docker_compose_service]
      target_label: container
      action: replace
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'resource-model-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9901']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:3000']