name: publish

on: [push]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
       docker build . --tag ghcr.io/arnaudlemaignen/resource-model-exporter:latest
       docker run ghcr.io/arnaudlemaignen/resource-model-exporter:latest
       docker push ghcr.io/arnaudlemaignen/resource-model-exporter:latest
